### ISSUE TITLE
Add an example fastq file from the Illumina NovaSeq / RTA3

### ISSUE THREAD

**Issue by colinbrislawn** [torognes/vsearch-data#3]
The Illumina NovaSeq use new RTA software which now reports 'binned' q-scores. See [NovaSeq 6000 System Quality Scores and
RTA3 Software (pdf)](https://www.illumina.com/content/dam/illumina-marketing/documents/products/appnotes/novaseq-hiseq-q30-app-note-770-2017-010.pdf)

I think this is within the fastq specification... but it's _a little funky_

Do you think an example of this would be helpful to add to the `fastq-test-suite`?

**Comment by torognes** [comment]
Thanks for the suggestion, but does this really change the format of the FASTQ files? It seems to me that it just uses a subset of the available quality score characters.

**Comment by colinbrislawn** [comment]
That's correct, this is still a valid fastq file, just with a reduced alphabet on the q-score line.

I'll close for now.
